butler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^stager/', include('stager.urls', namespace='stager')),
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social'))
]

stager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^login/$', views.login, name='login'),
        url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/stager/login/'}, name='logout'),
        url(r'^', views.dashboard, name='dashboard'),
        url(r'^add_repository/$', views.add_repository, name='add_repository'),
        url(r'^create_webhook/(?P<project_uuid>\w+)/$', views.create_webhook, name='create_webhook'),
        url(r'^webhooks/(?P<user_id>\w+)/(?P<project_id>\w+)/$', views.webhooks, name='webhooks'),
]

stager/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
import uuid


def generate_uuid4():
    return str(uuid.uuid4().hex)

class Project(models.Model):
    cod_uuid = models.CharField(max_length=40, primary_key=False, default=generate_uuid4, editable=False)
    repository_url = models.URLField(default="")
    name = models.CharField(max_length=40, default="")
    owner = models.ForeignKey(User)
    is_private = models.BooleanField(default=None)
    scm = models.CharField(max_length=10)
    language = models.CharField(max_length=40, default="")
    raw_json = models.TextField(default="")

class Webhook(models.Model):
    url = models.URLField(default="")
    project = models.ForeignKey(Project)
    owner = models.ForeignKey(User)
    description = models.CharField(max_length=40, default="Butler Alert")
    scope = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(default=datetime.now, blank=True)

class WebhookRequest(models.Model):
    pull_request = models.TextField()
    repository = models.TextField()
    actor = models.TextField()
    project = models.ForeignKey(Project)

stager/views.py
#coding: utf-8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.views.decorators.http import require_http_methods, require_POST
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.utils.text import slugify
from models import *
from django.core.urlresolvers import reverse

from requests_oauthlib import OAuth1

import ipdb
import json
import requests

def login(request):
    return render(request, 'stager/login.html', {})

@login_required
def dashboard(request):
    projects = Project.objects.filter(owner=request.user)
    webhooks = Webhook.objects.filter(owner=request.user)
    if not projects:
        projects = fetch_repositories(request.user)
    context = {'projects':projects, 'webhooks': webhooks}
    return render(request, 'stager/dashboard.html', context)

@require_POST
def add_repository(request):
    print request
    return HttpResponse("To be implemented")

@login_required
def create_webhook(request, project_uuid):
    """Given an object User and a project UUID, it creates a webhook for this project via API"""
    ipdb.set_trace()
    user = request.user
    project = Project.objects.get(cod_uuid=project_uuid)
    extra_data = json.loads(user.social_auth.values()[0]['extra_data'])
    webhook_url = settings.BUTLER_DEV_URL + project_uuid + "/"
    oauth = OAuth1(
                    settings.SOCIAL_AUTH_BITBUCKET_KEY,
                    settings.SOCIAL_AUTH_BITBUCKET_SECRET,
                    extra_data['access_token']['oauth_token'],
                    extra_data['access_token']['oauth_token_secret']
                )
    payload = {
                "description": "Butler Alert",
                "url": webhook_url,
                "active": True,
                "events": ["pullrequest:created", "pullrequest:updated", "pullrequest:fulfilled"]
            }

    project_slug = slugify(project.name)
    response = requests.post(settings.BITBUCKET_CREATE_WEBHOOK.format(owner=user.username, repo_slug=project_slug), auth=oauth, data=json.dumps(payload))
    ipdb.set_trace()
    if response.ok:
        data = json.loads(response.text)
        # persist webhook
        hook = Webhook()
        hook.url = data.get("url", webhook_url)
        hook.project = project
        hook.owner = user
        hook.description = data.get("description", "")
        hook.scope = str(data.get("events", ""))
        hook.save()
        # TODO: add a success message and redirect to stager/dashboard
        return HttpResponseRedirect(reverse('dashboard'))

    # TODO: add an error message here
    context = {}
    return render(request, 'stager/dashboard.html', context)

@csrf_exempt
@require_POST
def webhooks(request, user_id, project_id):
    """Parses webhooks requests and persists info into db"""
    body = json.loads(request.body)

    if request.META.get("HTTP_USER_AGENT", "") == settings.BITBUCKET_USER_AGENT:
        print "Webhook received from Bitbucket"
        return parse_bitbucket_webhook(body, project_id)
    elif request.META.get("HTTP_USER_AGENT", "") == settings.GITHUB_USER_AGENT:
        print "Webhook received from Github. It needs to be implemented"
        return parse_github_webhook(body)
    else:
        print "Couldn't recognize this service"
        return HttpResponseForbidden("Couldn't recognize this service",content_type="text/plain")

def parse_bitbucket_webhook(json_content, project_id):
    project = Project.objects.get(cod_uuid=project_id)
    pullrequest = json_content.get('pullrequest', False)
    repository = json_content.get('repository', {})
    actor = json_content.get('actor', {})
    try:
        repository_from_webhook = repository['links']['html']['href']
    except:
        repository_from_webhook = "ERROR"

    # Checks if repository url matches with repository sent via webhook
    repo_verified = (project.repository_url == repository_from_webhook)

    if repo_verified and pullrequest:
        webhook = Webhook()
        webhook.pull_request = json.dumps(pullrequest)
        webhook.repository = json.dumps(repository)
        webhook.actor = json.dumps(actor)
        webhook.project = project
        webhook.save()

        # TODO: We need to decide what exactly should be persisted. By now, I'm considering to persist these 3 dictionaries as plain text
        return HttpResponse("CHEGOU EM PAZ")
    return HttpResponseForbidden("We only support pull request webhooks. Please verify yours",content_type="text/plain")

def fetch_repositories(user, role="owner", persist=False):
    """Given an object User, it gets all repositories owned by this user"""

    extra_data = user.social_auth.values()[0]['extra_data']
    oauth = OAuth1(
                    settings.SOCIAL_AUTH_BITBUCKET_KEY,
                    settings.SOCIAL_AUTH_BITBUCKET_SECRET,
                    extra_data['access_token']['oauth_token'],
                    extra_data['access_token']['oauth_token_secret']
                    )
    response = requests.get(settings.BITBUCKET_REPOSITORIES_URL.format(username=user.username), auth=oauth)

    data = json.loads(response.text)
    projects = data.get("values")
    result = []
    for proj in projects:
        d = {
                "name": proj["name"],
                "scm": proj["scm"],
                "is_private": proj["is_private"],
                "language": proj["language"],
                "repository_url": proj["links"]["html"]["href"]
            }
        result.append(d)
        # TODO: verify if project already exists and update it
        obj = Project(**d)
        obj.owner = user
        obj.raw = json.dumps(proj)
        obj.save()
    return result

def parse_github_webhook(json_content):
    return HttpResponseForbidden("It needs to be implemented",content_type="text/plain")

stager/templates/stager/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Butler - Staging Servers using Docker</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "stager/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "stager/css/sb-admin.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "stager/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        {% block navigation %} {% endblock %}
        {% block content %} {% endblock %}
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static "stager/js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "stager/js/bootstrap.min.js" %}"></script>

</body>

</html>

stager/templates/stager/dashboard.html
{% extends 'stager/base.html' %}

{% block navigation %}
    {% include 'stager/navigation.html' %}
{% endblock %}

{% block content %}
<div id="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome, 
                    <small>{{ request.user.username }}</small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-file"></i> Blank Page
                    </li>
                </ol>
                <hr />
                {% if webhooks %}
                    <h3> Currently, we're monitoring {{ webhooks|length }} webhooks </h3>
                    {% for hook in webhooks %}
                        <p>{{ hook.url }}</p>
                        {% endfor %}
                {% else %}
                    <h3> Let's get started monitoring your projects! </h3>
                    {% if projects %}
                        <small>Click in one of the projects listed below to create a new webhhok for it</small>
                    {% else %}
                        <small>You need to be owner or admin of a project to be able to create a webhook for it.<small>
                    {% endif %}
                {% endif %}
                
                <hr />
                
                {% if projects %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Language</th>
                                <th>SCM</th>
                                <th>Private</th>
                                <th>Create Webhook</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td><a href={{ project.repository_url }} target="_blank">{{ project.name }}</a></td>
                                    <td>{{ project.language }}</td>
                                    <td>{{ project.scm }}</td>
                                    <td>{{ project.is_private }}</td>
                                    <td><a role="button" class="btn btn-info" href="{% url 'stager:create_webhook' project.cod_uuid %}">Create</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}

            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
{% endblock %}

stager/templates/stager/login.html
{% extends 'stager/base.html' %}

{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="jumbotron">
      <h1>Hello, baitinga!</h1>
        <p>Start using Butler for staging servers! </p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'social:begin' 'bitbucket' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}" role="button">Login with Bitbucket</a></p>
    </div>
</div>
{% endblock %}

stager/templates/stager/navigation.html
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Butler</a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu message-dropdown">
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading">
                                    <strong>John Smith</strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading">
                                    <strong>John Smith</strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading">
                                    <strong>John Smith</strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-footer">
                    <a href="#">Read All New Messages</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu alert-dropdown">
                <li>
                    <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">View All</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ request.user.username }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                <a href="{% url 'stager:logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
        </li>
        </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li class="active">
                <a href="#"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-table"></i> Tables</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-edit"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
            </li>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="demo" class="collapse">
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-file"></i> Blank Page</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>